modLoader="javafml"
loaderVersion="[66,)"
license="All-Rights-Reserved"
logoFile="icon.png"

[[mods]]
modId="minegeeks_for_servers"
version="1.0.0"
displayName="MineGeeks For Servers"
authors="Wellingtom Garcez"
description='''Cosmic mechanics and custom powers for Minecraft 26.3. Client and server support.'''

[[dependencies.minegeeks_for_servers]]
modId="forge"
mandatory=true
versionRange="[66.0.9,)"
ordering="NONE"
side="BOTH"

[[dependencies.minegeeks_for_servers]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="BOTH"
