modLoader="javafml"
loaderVersion="[66,)"
license="All-Rights-Reserved"

[[mods]]
modId="minegeeks_for_servers"
version="1.0.0"
displayName="MineGeeks For Servers"
authors="Wellingtom Garcez"
description='''Server-side cosmic generator and custom powers for Minecraft 26.3.'''

[[dependencies.minegeeks_for_servers]]
modId="forge"
mandatory=true
versionRange="[66.0.9,)"
ordering="NONE"
side="SERVER"

[[dependencies.minegeeks_for_servers]]
modId="minecraft"
mandatory=true
versionRange="[26.3,26.4)"
ordering="NONE"
side="SERVER"
