plugins {
    id 'net.fabricmc.fabric-loom' version project.loom_version
}

repositories {
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:" + project.minecraft_version
    implementation "net.fabricmc:fabric-loader:" + project.loader_version
    implementation "net.fabricmc.fabric-api:fabric-api:" + project.fabric_api_version
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

sourceSets.main.java.srcDirs = ["../common/src/main/java", "src/main/java"]

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}
