plugins {
    id 'org.quiltmc.loom.no_remap' version '1.15.1'
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.quiltmc.org/repository/release/' }
    maven { url = 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:26.3"
    implementation "net.fabricmc:fabric-loader:0.19.5"
    implementation "net.fabricmc.fabric-api:fabric-api:0.161.0+26.3"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

sourceSets.main.java.srcDirs = ["../common/src/main/java", "src/main/java"]
