plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.39'
}

version = '1.0.0'
group = 'com.minegeeks'

base {
    archivesName = 'minegeeks-for-servers-neoforge'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.neoforged:neoforge:26.3.0.52-beta'
}

sourceSets.main.java.srcDirs = ["../common/src/main/java", "src/main/java"]

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}
