org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.52-beta
mod_id=minegeeks_for_servers
mod_name=MineGeeks For Servers
mod_license=All-Rights-Reserved
mod_version=1.0.0
mod_group_id=com.minegeeks
